baseURL = "http://www.tkng.io/"
languageCode = "en-us"
title = "The Kubernetes Networking Guide"
theme = "hugo-theme-relearn"

[params]
    mermaid = false
    search = false
    disableInlineCopyToClipBoard = true
    editURL = "https://github.com/networkop/k8s-networking-guide/tree/master/content/${FilePath}"
